[tool.poetry]
name = "poetrytest"
version = "0.1.0"
description = ""
authors = ["MypaceEngine <spin.the.earth@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
